CONTEXT_MAPPING = {
        'air/high. pop.': 'air/urban air close to ground',
        'air/indoor': 'air/indoor',
        'air/low. pop.': 'air/non-urban air or from high stacks',
        'air/low. pop., long-term': 'air/low population density, long-term',
        'air/stratosphere + troposphere': 'air/lower stratosphere + upper troposphere',
        'emissions to air': 'air',
        'emissions to air/high. pop.': 'air/urban air close to ground',
        'emissions to air/low. pop.': 'air/non-urban air or from high stacks',
        'emissions to air/low. pop., long-term': 'air/low population density, long-term',
        'emissions to air/stratosphere + troposphere': 'air/lower stratosphere + upper troposphere',
        'emissions to soil': 'soil',
        'emissions to soil/agricultural': 'soil/agricultural',
        'emissions to soil/forestry': 'soil/forestry',
        'emissions to soil/industrial': 'soil/industrial',
        'water/groundwater, long-term': 'water/ground-, long-term',
        'water/river': 'water/surface water',
        'emissions to water': 'water',
        'emissions to water/groundwater': 'water/ground-',
        'emissions to water/groundwater, long-term': 'water/ground-, long-term',
        'emissions to water/lake': 'water/surface water',
        'emissions to water/ocean': 'water/ocean',
        'emissions to water/river': 'water/surface water',
        'emissions to water/river, long-term': 'water/surface water',
        'resources': 'natural resource/in ground',
        'resources/biotic': 'natural resource/biotic',
        'resources/in air': 'natural resource/in air',
        'resources/in ground': 'natural resource/in ground',
        'resources/in water': 'natural resource/in water',
        'resources/land': 'natural resource/land',
        'raw': 'natural resource/in ground',
        'raw/in water': 'natural resource/in water',
    }

UNITS_NORMALIZATION = {
    "a": "year",  # Common in LCA circles; could be confused with are
    "bq": "becquerel",
    "g": "gram",
    "gj": "gigajoule",
    "h": "hour",
    "ha": "hectare",
    "hr": "hour",
    "kbq": "kilobecquerel",
    "kg": "kilogram",
    "kgkm": "kilogram_kilometer",
    "km": "kilometer",
    "kj": "kilojoule",
    "kwh": "kilowatt hour",
    "l": "litre",
    "lu": "livestock unit",
    "m": "meter",
    "m*year": "meter_year",
    "m2": "square_meter",
    "m2*year": "square_meter_year",
    "m2a": "square_meter_year",
    "m2y": "square_meter_year",
    "m3": "cubic_meter",
    "m3*year": "cubic_meter_year",
    "m3a": "cubic_meter_year",
    "m3y": "cubic_meter_year",
    "ma": "meter_year",
    "metric ton*km": "ton_kilometer",
    "mj": "megajoule",
    "my": "meter_year",
    "nm3": "cubic_meter",
    "p": "unit",
    "personkm": "person_kilometer",
    "person*km": "person_kilometer",
    "pkm": "person_kilometer",
    "tkm": "ton_kilometer",
    "vkm": "vehicle_kilometer",
    'kg sw': "kilogram_separative_work_unit",
    'km*year': "kilometer_year",
    'metric ton*km': "ton_kilometer",
    'person*km': "person_kilometer",
    'wh': 'watt_hour',
}
