CONTEXT_MAPPING = {
    "air/indoor": "Airborne emissions", 
    "air/low population density, long-term": "Airborne emissions", 
    "air/lower stratosphere + upper troposphere": "Airborne emissions", 
    "air/non-urban air or from high stacks": "Airborne emissions", 
    "air/unspecified": "Airborne emissions", 
    "air/urban air close to ground": "Airborne emissions", 
    "natural resource/biotic": "Raw materials", 
    "natural resource/fossil well": "Raw materials", 
    "natural resource/in air": "Raw materials", 
    "natural resource/in ground": "Raw materials", 
    "natural resource/in water": "Raw materials", 
    "natural resource/land": "Raw materials", 
    "soil/agricultural": "Emissions to soil", 
    "soil/forestry": "Emissions to soil", 
    "soil/industrial": "Emissions to soil", 
    "soil/unspecified": "Emissions to soil", 
    "water/fossil well": "Waterborne emissions", 
    "water/ground-": "Waterborne emissions", 
    "water/ground-, long-term": "Waterborne emissions", 
    "water/ocean": "Waterborne emissions", 
    "water/surface water": "Waterborne emissions", 
    "water/unspecified": "Waterborne emissions", 
    "social/unspecified": "Social issues",
    "economic/primary production factor": "Economic issues",
    "inventory indicator/output flow": None,
    "inventory indicator/resource use": None,
    "inventory indicator/waste": None,
}

RANDOM_NAME_DIFFERENCES_MAPPING = {
    '2,4-D, dimethylamine salt': 'Dimethylamine',
    'Acids, unspecified': 'Acidity, unspecified',
    'Argon-40/kg': 'Argon-40',
    'Arsenic': 'Arsenic V',
    'Benzo(b,j,k)fluoranthene': 'Benzo(b)fluoranthene',
    'BOD5 (Biological Oxygen Demand)': 'BOD5, Biological Oxygen Demand',
    'BOD5 (Biological Oxygen Demand), NO': 'BOD5, Biological Oxygen Demand',
    'Chlorotoluron': 'Chlortoluron',
    'Chromium III': 'Chromium',
    'Coal, 26.4 MJ per kg': 'Coal, hard, unspecified, in ground',
    'Coal, 29.3 MJ per kg': 'Coal, hard, unspecified, in ground',
    'COD (Chemical Oxygen Demand)': 'COD, Chemical Oxygen Demand',
    'COD (Chemical Oxygen Demand), NO': 'COD, Chemical Oxygen Demand',
    'Dioxin, 2,3,7,8 Tetrachlorodibenzo-p-': 'Dioxins, measured as 2,3,7,8-tetrachlorodibenzo-p-dioxin',
    'Discarded fish, demersal': 'Discarded fish, demersal, to ocean',
    'Discarded fish, pelagic': 'Discarded fish, pelagic, to ocean',
    'Flurochloridone': 'Fluorochloridone',
    'Kaolin ore': 'Kaolinite, 24% in crude ore, in ground',
    'Lead-210/kg': 'Lead-210',
    'Metaldehyde (tetramer)': 'Metaldehyde',
    'Metolachlor, (S)': 'Metolachlor',
    'Nitrate compounds': 'Nitrate',
    'p-Xylene': 'Xylene',
    'Phenols, unspecified': 'Phenol',
    'Radioactive species, unspecified': 'Radioactive species, other beta emitters',
    'Radium-226/kg': 'Radium-226',
    'Radium-228/kg': 'Radium-228',
    'Sand, gravel and stone, extracted for use': 'Gravel, in ground',
    'Tri-allate': 'Triallate',
    '1-Butene': 'Butene',
    '2-Butene': 'Butene',
    'BTEX (Benzene, Toluene, Ethylbenzene, and Xylene), unspecified ratio': 'Benzene',
    'Calcium carbonate': 'Calcium, in ground',
    'Calcium chloride': 'Calcium, in ground',
    'Ethane, 1,1,2-trifluoro-, HFC-143': 'Ethane, 1,1,1-trifluoro-, HFC-143a',
    'Magnesium chloride': 'Magnesium, in ground',
    'Phosphate, NO': 'Phosphate',
    'Sulfur monoxide': 'Sulfur oxides',
}

MINOR_LAND_NAME_DIFFERENCES_MAPPING = {
    'Transformation, to rivers, artificial': 'Transformation, to river, artificial',
    'Transformation, to lakes, artificial': 'Transformation, to lake, artificial',
    'Transformation, to grassland/pasture/meadow': 'Transformation, to grassland, natural, for livestock grazing',
    'Transformation, to agriculture, mosaic': 'Transformation, to heterogeneous, agricultural',
    'Transformation, from grassland/pasture/meadow': 'Transformation, from grassland, natural, for livestock grazing',
    'Transformation, from grassland': 'Transformation, from grassland, natural, for livestock grazing',
    'Occupation, lakes, artificial': 'Occupation, lake, artificial',
    'Occupation, grassland/pasture/meadow': 'Occupation, grassland, natural, for livestock grazing',
}

MISSING_FOSSIL_AND_BIOGENIC_CARBON_MAPPING = {
    "Carbon dioxide": "Carbon dioxide, fossil",
    "Carbon dioxide, biogenic": "Carbon dioxide, non-fossil",
    "Carbon dioxide, fossil": "Carbon dioxide, fossil",
    "Carbon dioxide, land transformation": "Carbon dioxide, from soil or biomass stock",
    "Carbon dioxide, peat oxidation": "Carbon dioxide, from soil or biomass stock",
    "Methane": "Methane, fossil",
    "Methane, biogenic": "Methane, non-fossil",
    "Methane, fossil": "Methane, fossil",
    "Methane, land transformation": "Methane, from soil or biomass stock",
    "Methane, peat oxidation": "Methane, from soil or biomass stock",
    "Carbon monoxide": "Carbon monoxide, fossil",
    "Carbon monoxide, biogenic": "Carbon monoxide, non-fossil",
    "Carbon monoxide, fossil": "Carbon monoxide, fossil",
    "Carbon monoxide, land transformation": "Carbon monoxide, from soil or biomass stock",
}
